---
version: '3.7'

services:
  chatbot:
    image: ghcr.io/piweek/kaia:latest
    build: .
    restart: unless-stopped
    environment:
      MATTERMOST_URL: "${MATTERMOST_URL}"
      MATTERMOST_TOKEN: "${MATTERMOST_TOKEN}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"